### ISSUE TITLE
Explore ImageMagick trim capabilities for smarter image crops

### ISSUE THREAD

**Issue by sdillingham** [SCPR/AssetHost#10]
http://www.imagemagick.org/Usage/crop/#trim

Currently we use a manual crop gravity to determine how to cut square crops. Would be worth seeing if we can have smarter automatic cropping by better leveraging the native functions available in ImageMagick.
-----

AC

- [x] There is a better way to auto detect the best image gravity

**Comment by Ravenstine** [comment]
Right now, I've decided that the "largest face in photo" is the most consistent way detect the right gravity.  Other methods for when no faces are present don't appear to work very well, at least not yet.  Although it doubles the cost of processing images, I'm sticking with Rekognition for facial testing because it catches some edge cases(like faces that are sideways) that OpenCV doesn't, and it also gives us some more detailed image attributes.

I will continue to tinker with other methods, possibly switching to OpenCV if it makes sense, but will close this ticket because the facial method alone proves very sufficient.
