### ISSUE TITLE
Feature parity with current assethost version

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/AssetHost#13]
AC

- [ ] We're at feature parity in the new version of assethost (ex. supporting youtube and brightcove)

**Comment by Ravenstine** [comment]
Hmmm... wondering if there was a Github bug or a Zenhub bug.  This issue was not accessible the other day and appeared to be gone.  Anyway, I created an equivalent ticket the other day and closed it.  At the very least, the different video services are now supported.  It seems like it will now be a matter of re-implementing the existing tests in the new app and making sure they all pass.
