### ISSUE TITLE
Twitter no longer grabbing images

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/AssetHost#31]
Since the new assethost switch, twitter has not been able to pull images when tweet a link to an article. The twitter meta tags are there and I don't think we've changed them.  Could it be a read-permissions thing on assethost?

https://cards-dev.twitter.com/validator

Some test cases that should show twitter card images but don't:
* https://www.scpr.org/programs/take-two/2017/08/28/58841/journalist-relives-shielding-a-man-at-berkeley-alt/
* https://projects.scpr.org/maps/rent-burden/

AC:
- [x] twitter can read images from assethsot
- [x] tweets linking to our content have appropriate images

**Comment by Ravenstine** [comment]
Contacted Twitter support.  Waiting to hear back.

**Comment by Ravenstine** [comment]
Twitter never got back to me.

For some strange reason, Twitter does not like links to AssetHost images that use HTTPS protocol.  I can find no evidence as to why this would be the case.  Facebook can read our metadata perfectly fine.  I even went so far as to make updates to both SCPR.org and Outpost to output #public_urls with HTTPS so that our other Twitter meta links also use the same protocol... to no avail.  The only solution thus far is to force the "twitter:image" to use HTTP... which is a pretty terrible solution.  

Will continue to investigate because we will want to have HTTPS redirects for both SCPR.org and AssetHost in the future, and this is a block to that.  Closing this ticket because the images work with the cards now.
